# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 13:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pproject.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(max_length=20)),
                ('fuel', models.CharField(max_length=10)),
                ('transmission', models.CharField(max_length=10)),
                ('issue_date', models.DateField()),
                ('condition', models.CharField(max_length=20)),
                ('mileage', models.PositiveIntegerField()),
                ('model', models.CharField(max_length=10)),
                ('photos', models.ImageField(upload_to=b'')),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('rental_perion_begin', models.DateTimeField(validators=[pproject.validators.validate_rental_perion_begin])),
                ('rental_perion_end', models.DateTimeField(validators=[pproject.validators.validate_rental_perion_end])),
            ],
        ),
        migrations.CreateModel(
            name='CommonUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('own_cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_own_cars', to='pproject.Car')),
                ('tenant_cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tenant_cars', to='pproject.Car')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
