# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 23:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pproject.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(choices=[('', 'Transport type'), ('t1', 'type1'), ('t2', 'type2')], max_length=30)),
                ('fuel', models.CharField(choices=[('', 'Fuel type'), ('t1', 'type1'), ('t2', 'type2')], max_length=30)),
                ('transmission', models.CharField(choices=[('', 'Transmission type'), ('t1', 'type1'), ('t2', 'type2')], max_length=30)),
                ('issue_date', models.PositiveIntegerField()),
                ('condition', models.CharField(choices=[('', 'Condition'), ('t1', 'type1'), ('t2', 'type2')], max_length=20)),
                ('mileage', models.PositiveIntegerField()),
                ('model', models.CharField(max_length=10)),
                ('photo', models.ImageField(default='img/users_cars_photos/car.jpg', upload_to='img/users_cars_photos/')),
                ('price', models.PositiveIntegerField()),
                ('description_title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rental_perion_begin', models.DateField()),
                ('rental_perion_end', models.DateField()),
                ('country', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('street', models.CharField(max_length=100, null=True)),
                ('building', models.PositiveIntegerField(null=True)),
                ('docs', models.FileField(blank=True, null=True, upload_to='car_docs/')),
                ('is_insured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CommonUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(null=True, validators=[pproject.validators.validate_date_of_birth])),
                ('city', models.CharField(blank=True, max_length=60, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('vk', models.CharField(blank=True, max_length=60, null=True)),
                ('fb', models.CharField(blank=True, max_length=60, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(default='img/users_avatars/default.jpg', upload_to='img/users_avatars/')),
                ('docs_are_checked', models.BooleanField(default=False)),
                ('soc_networks_are_checked', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_own_cars', to='pproject.CommonUser'),
        ),
        migrations.AddField(
            model_name='car',
            name='renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_rent_cars', to='pproject.CommonUser'),
        ),
    ]
