# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('t1', 'type1'), ('t2', 'type2')], max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('t1', 'type1'), ('t2', 'type2')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(choices=[('t1', 'type1'), ('t2', 'type2')], max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('t1', 'type1'), ('t2', 'type2')], max_length=30),
        ),
    ]
