# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 17:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import pproject.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='issue_date',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2017)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.PositiveIntegerField(validators=[pproject.validators.validate_price, django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
