# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.FileField(blank=True, default=b'img/users_cars_photos/car.jpg', null=True, upload_to=b'img/users_cars_photos/'),
        ),
    ]
