# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pproject', '0002_auto_20170320_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
