# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 17:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pproject', '0002_auto_20170503_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(300)]),
        ),
    ]
