# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-27 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pproject', '0003_auto_20170503_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.FileField(default=b'img/users_cars_photos/car.jpg', upload_to=b'img/users_cars_photos/'),
        ),
    ]
