# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pproject', '0003_car_description_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonuser',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commonuser',
            name='fb',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='commonuser',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commonuser',
            name='photo',
            field=models.ImageField(default='img/users_avatars/default.jpg', upload_to='img/users_avatars/'),
        ),
        migrations.AddField(
            model_name='commonuser',
            name='vk',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
