# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 17:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import pproject.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pproject', '0004_auto_20170408_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonuser',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2017, 4, 8, 17, 9, 48, 593865, tzinfo=utc), validators=[pproject.validators.validate_date_of_birth]),
        ),
    ]
