# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-27 18:27
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import pproject.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pproject', '0004_auto_20170527_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.PositiveIntegerField(default=200, validators=[pproject.validators.validate_price, django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='rental_perion_begin',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='car',
            name='rental_perion_end',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
