# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 22:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pproject', '0005_auto_20170527_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentCarOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.TextField(blank=True, null=True)),
                ('comment_date', models.DateField(default=datetime.datetime.now)),
                ('is_interesting', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='commonuser',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commentcarowner',
            name='comment_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to='pproject.CommonUser'),
        ),
        migrations.AddField(
            model_name='commentcarowner',
            name='commented_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_user', to='pproject.CommonUser'),
        ),
    ]
