# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import pproject.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pproject', '0005_commonuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonuser',
            name='date_of_birth',
            field=models.DateField(validators=[pproject.validators.validate_date_of_birth]),
        ),
    ]
