# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pproject', '0006_auto_20170410_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonuser',
            name='own_cars',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_own_cars', to='pproject.Car'),
        ),
        migrations.AlterField(
            model_name='commonuser',
            name='tenant_cars',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tenant_cars', to='pproject.Car'),
        ),
    ]
