# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pproject', '0007_auto_20170602_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentcarowner',
            name='is_interesting',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
