# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pproject', '0007_auto_20170410_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonuser',
            name='city',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
