# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pproject', '0009_auto_20170423_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='photos',
        ),
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(default='img/users_cars_photos/car.jpg', upload_to='img/users_cars_photos/'),
        ),
    ]
