# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pproject', '0009_car_times_rented'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='original_renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_user_rent_cars', to='pproject.CommonUser'),
        ),
    ]
