# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-03 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pproject', '0010_car_original_renter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='original_renter',
        ),
        migrations.RemoveField(
            model_name='car',
            name='times_rented',
        ),
    ]
