# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pproject', '0010_auto_20170427_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonuser',
            name='own_cars',
        ),
        migrations.RemoveField(
            model_name='commonuser',
            name='tenant_cars',
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_own_cars', to='pproject.CommonUser'),
        ),
        migrations.AddField(
            model_name='car',
            name='renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_rent_cars', to='pproject.CommonUser'),
        ),
    ]
