# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-03 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pproject', '0011_auto_20170603_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='times_rented',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
