# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pproject', '0011_auto_20170427_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='building',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='city',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='country',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='street',
            field=models.TextField(null=True),
        ),
    ]
