# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 14:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pproject', '0012_car_times_rented'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.TextField(blank=True, null=True)),
                ('comment_date', models.DateField(default=datetime.datetime.now)),
                ('is_interesting', models.PositiveIntegerField(blank=True, default=0)),
                ('unauthed_user_email', models.EmailField(max_length=254, null=True)),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_car_author', to='pproject.CommonUser')),
                ('commented_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_car', to='pproject.Car')),
            ],
        ),
    ]
