# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pproject', '0013_auto_20170429_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='docs',
            field=models.FileField(blank=True, null=True, upload_to='car_docs/'),
        ),
        migrations.AddField(
            model_name='car',
            name='is_insured',
            field=models.BooleanField(default=False),
        ),
    ]
