# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pproject', '0014_auto_20170429_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='building',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
