# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pproject', '0015_auto_20170429_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('', 'Transport type'), ('t1', 'type1'), ('t2', 'type2')], max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('', 'Condition'), ('t1', 'type1'), ('t2', 'type2')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(choices=[('', 'Fuel type'), ('t1', 'type1'), ('t2', 'type2')], max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('', 'Transmission type'), ('t1', 'type1'), ('t2', 'type2')], max_length=30),
        ),
    ]
