# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import pproject.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pproject', '0016_auto_20170501_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonuser',
            name='date_of_birth',
            field=models.DateField(null=True, validators=[pproject.validators.validate_date_of_birth]),
        ),
    ]
