# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-07-27 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.TextField(),
        ),
    ]
